# These are supported funding model platforms
# Kingken Global Travel Agency Ltd

github: [kingkenglobal, EzeKennethOgbonna] 
patreon: kingkenglobal
open_collective: kingken-global
ko_fi: kingkenglobal
tidelift: npm/kingken-global-platform
community_bridge: kingken-global
liberapay: kingkenglobal
issuehunt: kingkenglobal
lfx_crowdfunding: kingken-global
polar: kingkenglobal
buy_me_a_coffee: kingkenglobal
thanks_dev: contact@kingkenglobal.com.ng

custom:
  - https://www.kingkenglobal.com.ng
  - https://www.kingkenglobal.com.ng/support
  - https://www.kingkenglobal.com.ng/partnership
  - mailto:info@kingkenglobal.com.ng
  - mailto:contact@kingkenglobal.com.ng
